version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10

    # Group packages into shared PR
    groups:
      build:
        patterns:
          - '@babel/*'
          - 'babel-*'
          - 'tsx'
          - 'webpack'
          - 'webpack-*'
          - 'terser-webpack-plugin'

      lint:
        patterns:
          - 'prettier'
          - 'stylelint'
          - 'stylelint-*'

      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
          - 'typescript-eslint'

      logging:
        patterns:
          - '*-pino'
          - '*-pino-format'
          - 'pino'
          - 'pino-*'

      tools:
        patterns:
          - 'husky'
          - 'eslint-*'
          - 'eslint'
          - 'nodemon'
          - 'npm-run-all'
          - 'lodash'
          - 'source-map-loader'
          - 'sass-*'
          - 'postcss-*'

      vitest:
        patterns:
          - 'vitest'
          - 'vitest-*'
          - '@vitest/*'

      types:
        patterns:
          - '@types/*'

    # Allow releases to settle into a stable state before updating
    cooldown:
      default-days: 5
      semver-major-days: 20
      semver-minor-days: 7
      semver-patch-days: 3

    schedule:
      interval: "cron"
      cronjob: "0 9 1 * *"
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      # Include direct package.json updates
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /

    schedule:
      interval: "cron"
      cronjob: "0 9 1 * *"
      timezone: 'Europe/London'
